# Generated by Django 3.0.3 on 2020-08-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
